export { default as Header } from './Main/Header'
export { default as MainBanner } from './Main/MainBanner';
export { default as MenSection } from './Main/MenSection';
export { default as WomenSection } from './Main/WomenSection';
export { default as JewelerySection } from './Main/JewelerySection';
export { default as ExploreSection } from './Main/ExploreSection';
export { default as SocialSection } from './Main/SocialSection';
export { default as SubscribeSection } from './Main/SubscribeSection';
export { default as FooterSection } from './Main/FooterSection';
export { default as Layout } from './Layout/Layout';